### ISSUE TITLE
Errata: pg 45

### ISSUE THREAD

**Issue by csajedi** [code0wl/Multiplayer-Phaser-game#10]
Hi, thanks for making the great book. I figured here was probably a practical place to report an errata. This one is simple, on pg. 45 the code sample is listed as being at: 
"Listing 4-16. src/client/controls/keyboard.model.ts" 

However it is actually keyboard.class.ts that we are updating in listing 4-16.

Regards

**Comment by csajedi** [comment]
Listing 5-2 also similarly mislabeled: states we are at player.class.ts but instead we are looking at the game class

**Comment by code0wl** [comment]
@csajedi Thank you very much for this! I will make sure these get corrected in the second print. I've contacted Apress for a fix ASAP. For the printed books that might be an issue but we can definitely fix the PDF version.  I've updated the readme and included a special thanks section 👍 

I will leave this issue open as it might help someone.

**Comment by code0wl** [comment]
Publisher is currently making the changes, will close
